/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dawid_ckw.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BillResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5130537205993262281L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BillResponse\",\"namespace\":\"com.dawid_ckw.avro\",\"fields\":[{\"name\":\"children\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Bill\",\"fields\":[{\"name\":\"startPeriod\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"endPeriod\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"amount\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<BillResponse> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BillResponse> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BillResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BillResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BillResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BillResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BillResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BillResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BillResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<com.dawid_ckw.avro.Bill> children;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BillResponse() {}

  /**
   * All-args constructor.
   * @param children The new value for children
   */
  public BillResponse(java.util.List<com.dawid_ckw.avro.Bill> children) {
    this.children = children;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return children;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: children = (java.util.List<com.dawid_ckw.avro.Bill>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'children' field.
   * @return The value of the 'children' field.
   */
  public java.util.List<com.dawid_ckw.avro.Bill> getChildren() {
    return children;
  }


  /**
   * Sets the value of the 'children' field.
   * @param value the value to set.
   */
  public void setChildren(java.util.List<com.dawid_ckw.avro.Bill> value) {
    this.children = value;
  }

  /**
   * Creates a new BillResponse RecordBuilder.
   * @return A new BillResponse RecordBuilder
   */
  public static com.dawid_ckw.avro.BillResponse.Builder newBuilder() {
    return new com.dawid_ckw.avro.BillResponse.Builder();
  }

  /**
   * Creates a new BillResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BillResponse RecordBuilder
   */
  public static com.dawid_ckw.avro.BillResponse.Builder newBuilder(com.dawid_ckw.avro.BillResponse.Builder other) {
    if (other == null) {
      return new com.dawid_ckw.avro.BillResponse.Builder();
    } else {
      return new com.dawid_ckw.avro.BillResponse.Builder(other);
    }
  }

  /**
   * Creates a new BillResponse RecordBuilder by copying an existing BillResponse instance.
   * @param other The existing instance to copy.
   * @return A new BillResponse RecordBuilder
   */
  public static com.dawid_ckw.avro.BillResponse.Builder newBuilder(com.dawid_ckw.avro.BillResponse other) {
    if (other == null) {
      return new com.dawid_ckw.avro.BillResponse.Builder();
    } else {
      return new com.dawid_ckw.avro.BillResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for BillResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BillResponse>
    implements org.apache.avro.data.RecordBuilder<BillResponse> {

    private java.util.List<com.dawid_ckw.avro.Bill> children;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dawid_ckw.avro.BillResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.children)) {
        this.children = data().deepCopy(fields()[0].schema(), other.children);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BillResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dawid_ckw.avro.BillResponse other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.children)) {
        this.children = data().deepCopy(fields()[0].schema(), other.children);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'children' field.
      * @return The value.
      */
    public java.util.List<com.dawid_ckw.avro.Bill> getChildren() {
      return children;
    }


    /**
      * Sets the value of the 'children' field.
      * @param value The value of 'children'.
      * @return This builder.
      */
    public com.dawid_ckw.avro.BillResponse.Builder setChildren(java.util.List<com.dawid_ckw.avro.Bill> value) {
      validate(fields()[0], value);
      this.children = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'children' field has been set.
      * @return True if the 'children' field has been set, false otherwise.
      */
    public boolean hasChildren() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'children' field.
      * @return This builder.
      */
    public com.dawid_ckw.avro.BillResponse.Builder clearChildren() {
      children = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BillResponse build() {
      try {
        BillResponse record = new BillResponse();
        record.children = fieldSetFlags()[0] ? this.children : (java.util.List<com.dawid_ckw.avro.Bill>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BillResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<BillResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BillResponse>
    READER$ = (org.apache.avro.io.DatumReader<BillResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










