/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dawid_ckw.avro;
@org.apache.avro.specific.AvroGenerated
public enum PeriodType implements org.apache.avro.generic.GenericEnumSymbol<PeriodType> {
  YEAR, MONTH, DAY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PeriodType\",\"namespace\":\"com.dawid_ckw.avro\",\"symbols\":[\"YEAR\",\"MONTH\",\"DAY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
